add sorting option for filters
i-love-flamingo/flamingo pull request #172
Opened 2020-11-02 09:55 UTC by Ompluscator

Added option for web.Filter to be prioritised. By default, priority for all filters is 0, until it's specified differently. During web.ChainFilter initialisation, filters are stored in descending order.

2020-11-19 13:24 UTC, bastianccm requested changes

2020-11-19 13:24 UTC, bastianccm commented on framework/web/filter.go
> +	var filters []Filter
Directly initialize the slice with the length of sf

2020-11-19 13:25 UTC, tessig commented
Please also drop a sentence to framework/web/docs/ReadmeRouter.md

2020-11-24 09:28 UTC, tessig requested changes

2020-11-24 09:28 UTC, tessig commented on framework/web/filter_test.go
> +		chain := NewFilterChain(nil, tc.filters...)
I would prefer named test cases and runs in sub tests, via
```
t.Run(tc.name, func(t *testing.T) { ... })
```

2020-11-25 08:43 UTC, tessig approved these changes
Very nice work. Thank you!

2020-11-25 08:57 UTC, bastianccm approved these changes

2020-11-25 09:01 UTC, tessig commented
@Ompluscator Would you please rebase this branch on master? Afterwards we merge directly :)

2020-11-26 07:05 UTC, Ompluscator commented
> @Ompluscator Would you please rebase this branch on master? Afterwards we merge directly :)

Done :)

2020-12-03 14:15 UTC, merged