ci: add nancy
i-love-flamingo/flamingo pull request #184
Opened 2021-02-18 08:43 UTC by jeinfeldt

Hello,

we would benefit from using [Nancy](https://github.com/sonatype-nexus-community/nancy) to check our dependencies.
@tessig opened a PR for this previously https://github.com/i-love-flamingo/flamingo/pull/69
before `go.mod` was fully supported.

Since flamingo does not use travis anymore for CI, lets try with github actions.
Workflow suggested by: https://github.com/marketplace/actions/nancy-for-github-actions

2021-02-25 12:40 UTC, carstendietrich commented
We could move this to the `Static checks` part, and we should have a look at https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events to run the dependency check on a daily basis..

2021-02-25 14:09 UTC, carstendietrich commented
@jeinfeldt please check the scheduled trigger and try to do a go get on etcd to override the vuln dependency

2021-03-11 14:12 UTC, tessig requested changes

2021-03-11 14:12 UTC, tessig commented on .github/workflows/main.yml
> +        with:
we don't need this, it's already above

2021-03-11 14:12 UTC, tessig commented on .github/workflows/daily.yml
> +          go-version: ^1.13
just take the most actual version via 1.*

2021-03-11 14:40 UTC, tessig approved these changes
very nice, thanks!

2021-03-11 14:41 UTC, merged